# Generated by Django 4.2.5 on 2023-09-21 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disciplinaEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='tarefaEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=320)),
                ('data_entrega', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_disciplina.alunoentidade')),
                ('disciplina', models.ManyToManyField(to='controle_disciplina.disciplinaentidade')),
            ],
        ),
    ]
